App_Integration/App_Integration/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.integrate.urls')),
    url(r'^djangogold/', include('apps.djangogold.urls', namespace='gold')),
    url(r'^randomword/', include('apps.rndwordgen.urls', namespace='rand')),
    url(r'^timedisplay/', include('apps.timedisplay.urls', namespace='time')),
    url(r'^courses/', include('apps.coursesapp.urls', namespace='courses')),
    url(r'^loginreg/', include('apps.loginreg.urls', namespace='login')),

]

App_Integration/apps/coursesapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add$', views.add, name='add'),
    url(r'^usertocourse/$', views.add_to_course, name='usertocourse'),
    url(r'^remove/(?P<id>\d+)$', views.remove, name='remove'),
    url(r'^remove/delete/(?P<id>\d+)$', views.delete, name='delete'),
]

App_Integration/apps/coursesapp/models.py
from __future__ import unicode_literals
from django.db import models
from ..loginreg.models import User

# Create your models here.
class Course(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=1000)
    userskey = models.ManyToManyField(User, related_name="courseskey")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

App_Integration/apps/coursesapp/views.py
from django.shortcuts import render, redirect
from .models import Course, User
from django.core.urlresolvers import reverse

def index(request):
    context = {
        'courses' : Course.objects.all(),
        'users' : User.objects.all(),
    }
    return render(request,'coursesapp/index.html', context)

def add(request):
    new_course = Course.objects.create(name=request.POST['name'], description=request.POST['description'])
    new_course.save()
    return redirect(reverse('courses:index'))

def remove(request, id):
    context = {
        'remove_course' : Course.objects.get(id=id),
    }
    return render(request, 'coursesapp/remove.html', context)

def delete(request, id):
    delete_course = Course.objects.get(id=id)
    delete_course.delete()
    return redirect(reverse('courses:index'))

def add_to_course(request):
    course = Course.objects.get(id=request.POST['course_id'])
    user = User.objects.get(id=request.POST['user_id'])
    course.userskey.add(user)
    return redirect(reverse('courses:index'))

App_Integration/apps/coursesapp/templates/coursesapp/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Courses</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'coursesapp/css/index.css' %}">
  </head>
  <body>
    <div id="wrapper">
      <h3>Add a new course</h3>
      <div id="add_box_left">
        <p>Name:</p>
        <p>Description:</p>
      </div><!--add_box_left end -->
      <div id="add_box_right">
        <form action="add" method="post">
          {% csrf_token %}
          <input type="text" name="name" value="">
          <textarea name="description"></textarea>
          <button type="submit" name="button">Add Course</button>
        </form>
      </div><!-- add_box_right end -->
      <h3>Courses</h3>
      <table>
        <tr>
          <th>Course Name</th>
          <th>Description</th>
          <th>Date Added</th>
          <th>#Users</th>
          <th>Actions</th>
        </tr>
        {% for course in courses %}
        <tr>
          <td>{{course.name}}</td>
          <td>{{course.description}}</td>
          <td>{{course.created_at}}</td>
          <td>{{course.userskey.count}}</td>
          <td><a href='remove/{{course.id}}'>Remove</a></td>
        </tr>
        {% endfor %}
      </table>
      <div id="add_users">
        <form action="{% url 'courses:usertocourse' %}" method="post">
          {% csrf_token %}
          <select name="user_id">
            {% for user in users %}
            <option value="{{user.id}}">{{user.id}}</option>
            {% endfor %}
          </select>
          <select name="course_id">
            {% for course in courses %}
            <option value="{{course.id}}">{{course.name}}</option>
            {% endfor %}
          </select>
          <button type="submit" name="add_user_to_course">Add user to course</button>
        </form>

      </div><!-- add_users end -->
    </div><!-- wrapper end -->
  </body>
</html>

App_Integration/apps/coursesapp/templates/coursesapp/remove.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Remove Course</title>
  </head>
  <body>
    <h3>Are you sure you want to delete the below course:</h3>
    <p>Name: <p>{{remove_course.name}}</p></p>
    <p>Description: <p>{{remove_course.description}}</p></p>
    <a href={% url 'courses:index' %}><button type="button" name="cancel">Cancel</button></a>
    <a href="delete/{{remove_course.id}}"><button type="button" name="delete">Delete Course: {{remove_course.id}}</button></a>
  </body>
</html>